version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - data-pipeline-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - data-pipeline-network
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092


  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - data-pipeline-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admindb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    networks:
      - data-pipeline-network
    ports:
      - "8081:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MODE=master
      # - JAVA_HOME=/opt/bitnami/java
      # - PATH=/opt/bitnami/java/bin:$PATH
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./conf/spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh

  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    networks:
      - data-pipeline-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    depends_on:
      - kafka
      - spark-master
    networks:
      - data-pipeline-network
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./postgresql-42.7.3.jar:/home/jovyan/postgresql-42.7.3.jar
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: >
      bash -c "pip install kafka-python &&
      start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

# networks:
#   data-pipeline-network:
#     driver: bridge

networks:
  data-pipeline-network:
    external: true
